name: the conformist manifesto
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Conformist Manifesto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a1111b'
    - '#ecd6d9'
    - '#c08899'
    - '#a2596d'
  brandStrength: 0.5625
  lightness: 0.20299724978394806
  saturation: 0.8913004801142961
  rhythmicContrast: 0.1296971805859357
purpose: []
