name: the conformist manifesto
favicon: null
layout_spectrum: 0.7085009478032589
typography_spectrum: 0.1863038786686957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0857690223492682
  lightness: 0.20299724978394806
  saturation: 0.8913004801142961
  rhythmicContrast: 0.1296971805859357
purpose: []
