name: the conformist manifesto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00052
title: The Conformist Manifesto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3d3d3'
    - '#ac783e'
    - '#4d2d0d'
    - '#090501'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
