name: the conformist manifesto
favicon: null
layout_spectrum: 0.43051
typography_spectrum: 0.29141
title: The Conformist Manifesto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010c10'
    - '#14272d'
    - '#3f646c'
    - '#7499a1'
    - '#a3c4cb'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
